name: climate-rl-mres
channels:
  - pytorch
  - nvidia
  - conda-forge
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - ale-py=0.8.1
  - alembic=1.13.1
  - alsa-lib=1.2.9
  - anyio=4.4.0
  - aom=3.7.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blessed=1.20.0
  - blosc=1.21.5
  - box2d-py=2.3.8
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.16.0
  - cartopy=0.23.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - climlab=0.8.2
  - climlab-cam3-radiation=0.2
  - climlab-emanuel-convection=0.2
  - climlab-rrtmg=0.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorful=0.5.6
  - colorlog=6.8.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cryptography=42.0.5
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - curl=8.7.1
  - cycler=0.12.1
  - cython=0.29.37
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.8
  - docker-pycreds=0.4.0
  - docstring_parser=0.16
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - farama-notifications=0.0.4
  - ffmpeg=6.1.0
  - filelock=3.15.3
  - flexcache=0.3
  - flexparser=0.3.1
  - fluidsynth=2.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freeglut=3.4.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozendict=2.4.4
  - frozenlist=1.4.1
  - fsspec=2024.6.0
  - future=1.0.0
  - gdbm=1.18
  - geos=3.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - git=2.42.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glfw=3.4
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - google-api-core=2.19.1
  - google-auth=2.30.0
  - googleapis-common-protos=1.63.2
  - gpustat=1.1.1
  - graphite2=1.3.14
  - greenlet=3.0.3
  - grpcio=1.54.3
  - gst-plugins-base=1.22.5
  - gstreamer=1.22.5
  - gymnasium=0.29.1
  - gymnasium-all=0.29.1
  - gymnasium-atari=0.29.1
  - gymnasium-box2d=0.29.1
  - gymnasium-classic_control=0.29.1
  - gymnasium-mujoco=0.29.1
  - gymnasium-other=0.29.1
  - gymnasium-toy_text=0.29.1
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=7.3.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.7
  - imageio=2.34.1
  - imageio-ffmpeg=0.5.1
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - intel-openmp=2024.1.2
  - ipykernel=6.29.4
  - ipython=8.25.0
  - isoduration=20.11.0
  - jack=1.9.22
  - jasper=4.0.0
  - jax-jumpy=1.0.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libarrow=12.0.1
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libavif16=1.0.3
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libcblas=3.9.0
  - libccd-double=2.1
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcups=2.3.3
  - libcurand=10.3.6.39
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.18
  - libdrm=2.4.121
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.49
  - libgrpc=1.54.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libmad=0.15.1b
  - libmujoco=2.3.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnuma=2.0.18
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopencv=4.7.0
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-intel-npu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libthrift=0.18.1
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lodepng=20220109
  - lz4=4.3.3
  - lz4-c=1.9.4
  - mako=1.3.5
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - metpy=1.6.2
  - mistune=3.0.2
  - mkl=2024.1.0
  - moviepy=1.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.31.3
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - mujoco-python=2.3.7
  - multidict=6.0.5
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.6.4
  - nettle=3.9.1
  - networkx=3.3
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - nvidia-ml-py=12.555.43
  - ocl-icd=2.3.2
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.6
  - optuna=3.6.1
  - opusfile=0.12
  - orc=1.9.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathtools=0.1.2
  - pcre2=10.40
  - perl=5.34.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pint=0.24
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - ply=3.11
  - pooch=1.8.2
  - portaudio=19.6.0
  - portmidi=2.0.4
  - proglog=0.1.9
  - proj=9.3.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.21.12
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - py-spy=0.3.14
  - pyarrow=12.0.1
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pybind11-abi=4
  - pycparser=2.22
  - pydantic=1.10.16
  - pygame=2.5.2
  - pyglfw=2.7.0
  - pygments=2.18.0
  - pyopengl=3.1.6
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - qt-main=5.15.8
  - rav1e=0.6.6
  - ray-core=2.8.1
  - ray-default=2.8.1
  - ray-tune=2.8.1
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.18.1
  - rsa=4.9
  - s2n=1.3.49
  - scipy=1.13.1
  - sdl2=2.28.5
  - sdl2_image=2.6.3
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.20.2
  - send2trash=1.8.3
  - sentry-sdk=2.6.0
  - setproctitle=1.3.3
  - setuptools=70.1.0
  - shapely=2.0.4
  - shimmy=1.3.0
  - shimmy-atari=1.3.0
  - shtab=1.7.1
  - sip=6.7.12
  - six=1.16.0
  - smart_open=7.0.4
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=2.0.31
  - sqlite=3.46.0
  - stable-baselines3=2.3.2
  - stack_data=0.6.2
  - svt-av1=1.7.0
  - sympy=1.12.1
  - tbb=2021.12.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - tephi=0.3.0
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tinyxml2=9.0.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tyro=0.8.4
  - tzdata=2024a
  - ucx=1.14.1
  - uri-template=1.3.0
  - urllib3=2.2.2
  - virtualenv=20.21.0
  - wandb=0.16.5
  - wayland=1.23.0
  - wayland-protocols=1.36
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.16.0
  - x264=1!164.3095
  - x265=3.5
  - xarray=2024.6.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxinerama=1.1.5
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.6
